#!/bin/sh
# check if we are on real system
if [ -z "${IPKG_INSTROOT}" ]; then
    echo "Removing rc.d symlink for shadowsocksr"
     /etc/init.d/shadowsocksr disable
     /etc/init.d/shadowsocksr stop
    echo "Removing firewall rule for shadowsocksr"
	  uci -q batch <<-EOF >/dev/null
		delete firewall.shadowsocksr
		commit firewall
EOF
if [ "GFW" = "GFW" ] ;then
sed -i '/conf-dir/d' /etc/dnsmasq.conf 
/etc/init.d/dnsmasq restart 
fi
fi
exit 0
